### ISSUE TITLE
Write Project documentation in README file

### ISSUE THREAD

**Issue by MostafaAE** [O-Gamal/TEA-Tiny-Encryption-Algorithm#25]
Update README file with all technical details of the project:

> This link could help a lot: https://www.makeareadme.com/

**Comment by M0stafaAmin** [comment]
Mon 11/1/2021
i write a brief documentation about how we implement TEA function and all bugs which have been solved 
this link helped me with markdown syntax https://www.markdownguide.org/basic-syntax/

**Comment by MostafaSaad7** [comment]
Mon  11/1/2021
I wrote a brief summary about Tiny encryption algorithm and attached GIF illustrate Handling exceptions for key inputs .
