### ISSUE TITLE
Test the program

### ISSUE THREAD

**Issue by MostafaAE** [O-Gamal/TEA-Tiny-Encryption-Algorithm#32]
### TESTING
**Test the program using various test cases to find and solve any bugs**

This website generates random text [https://www.lipsum.com](url), it will be very useful when we want to generate various test cases to detect any bugs in the program.

**Comment by O-Gamal** [comment]
Sat 9/1/2021
There is a bug in main.asm when we enter a large string then enter another string with lower size the encryption outputs wrong values in MsgBox because teaIn keeps the previously entered values in it.
I made an issue for this bug check #47 for more info.
