### ISSUE TITLE
Bug in main.asm when we present the output in Message Box, sometimes the output result is wrong when a character is encrypted to '\0' (NULL char)

### ISSUE THREAD

**Issue by Mariamgad** [O-Gamal/TEA-Tiny-Encryption-Algorithm#43]
### BUG in main.asm
*main.asm have a bug: When we present the output in Message Box, sometimes the output result is wrong when a character is encrypted to '\0' (NULL char) because MsgBox prints the string till it find a NULL char.*

*Failed test cases:*

Enter your text: asdfklsjalfkjaslkjfaslkf
Enter 4 keys
Enter Key 1: 1
Enter Key 2: 2
Enter Key 3: 3
Enter Key 4: 4

*Program Output:*
![image](https://user-images.githubusercontent.com/47721226/104063529-fc3af080-5204-11eb-8cc9-15c5e72ef2e8.png)

❌

The output result is 4 characters only not 24!
-------------------------------------------------------------------------------------------------------------------------

*Expected Output:*

Encrypted: îٌَF ش-اُd┌قثنB¤:~≡█|hر

✔️

**Comment by MostafaAE** [comment]
Sat 9/1/2021
Me and @MostafaSaad7 collaborated together and solved this bug by replacing every charcater encrypted to NULL char ('\0') by a space char (' ').

**inserted code:**

```
copyTeaOut:
        
        mov al, [ebx]
        ;if (char == '\0') replace with ' '
        cmp al, 0
        jne putChar
        mov al, ' '

        putChar:
            mov [edx], al

        inc ebx
        inc edx

    LOOP copyTeaOut
```
