### ISSUE TITLE
Handling Exceptions for Keys

### ISSUE THREAD

**Issue by M0stafaAmin** [O-Gamal/TEA-Tiny-Encryption-Algorithm#45]
When we enter a string or a blank or values greater than (2^32)-1, The ReadDec function puts (0H) in the key.
We should handle these exceptions and make the key accept only digits and ignore spaces.

**Comment by MostafaAE** [comment]
Sun 10/1/2021
I and @O-Gamal Collaborated together and implemented a procedure for handling exceptions for the key (handleKey).
